import {getPeopleReport} from './people.js';
import {getDiplomacyReport} from './diplomacy.js';

export function renderPeople(state, {esc, money, kv, progress}) {
  const report = getPeopleReport(state);
  const requests = report.requests.filter(request => request.status === 'pending' || request.status === 'promised');
  return `<section class="people-section" aria-labelledby="people-title"><div class="section-heading"><h3 id="people-title">The people behind the fleet</h3><span class="badge">${Math.round(report.summary.enjoyment)}% enjoyment</span></div><p class="caption social-notice">${esc(report.notice)}</p>
    <section class="inner-panel people-requests" aria-label="Pilot requests"><h3>Requests & disputes <span class="muted">· ${requests.filter(request => request.status === 'pending').length} awaiting a decision</span></h3>${requests.length ? requests.map(request => `<article class="social-request" data-request="${esc(request.id)}"><div class="section-heading"><strong>${esc(request.title)}</strong><span class="badge warning">${request.status === 'promised' ? 'Promised by' : 'Due watch'} ${request.dueTurn}</span></div><p class="modal-copy">${esc(request.text)}</p><div class="request-choices">${request.choices.map(choice => `<button class="button choice-button" data-action="peopleRespond" data-request-id="${esc(request.id)}" data-choice-id="${esc(choice.id)}" ${choice.disabled || state.result ? 'disabled' : ''}><strong>${esc(choice.label)}${choice.cost ? ' · '+money(choice.cost) : ''}</strong><span>${esc(choice.description)}</span></button>`).join('')}</div></article>`).join('') : '<p class="empty-state">No unanswered requests. Pilot expectations develop as the campaign progresses.</p>'}</section>
    <details class="social-disclosure" open><summary>Pilot cohorts <span>Preferences, fatigue & participation</span></summary><div class="cohort-grid">${report.cohorts.map(cohort => `<article class="inner-panel cohort-card" data-cohort="${esc(cohort.id)}"><div class="section-heading"><h3>${esc(cohort.name)}</h3><span class="badge">${cohort.count} pilots</span></div><p class="modal-copy">${esc(cohort.preference)}</p><div class="stat-cluster"><span>Ready ≈ ${cohort.readyEstimate}</span><span>Trust ${Math.round(cohort.trust)}%</span><span>Fatigue ${Math.round(cohort.fatigue)}%</span></div>${kv('Enjoyment',`${Math.round(cohort.enjoyment)}%`)}${progress(cohort.enjoyment)}<div class="button-row"><button class="button" data-action="peopleRest" data-cohort-id="${esc(cohort.id)}" ${!cohort.count || cohort.resting || state.result ? 'disabled' : ''}>${cohort.resting ? 'Protected rest active' : 'Give protected rest'}</button><button class="button" data-action="peopleRecognize" data-cohort-id="${esc(cohort.id)}" ${!cohort.count || cohort.recognitionCooldown || state.result ? 'disabled' : ''}>${cohort.recognitionCooldown ? `Recognition in ${cohort.recognitionCooldown} watches` : `Recognize · ${money(cohort.recognitionCost)}`}</button></div><p class="caption">Protected rest temporarily removes these pilots from attendance.</p></article>`).join('')}</div></details>
    <details class="social-disclosure"><summary>Corporation policies <span>Access, attendance & ship reimbursement</span></summary><div class="policy-grid">${report.policies.map(policy => `<form class="inner-panel" data-policy-form="${esc(policy.id)}"><label class="form-field">${esc(policy.name)}<select name="value">${policy.options.map(option => `<option value="${esc(option.id)}" ${option.id === policy.value ? 'selected' : ''}>${esc(option.name)}</option>`).join('')}</select></label><div class="policy-explanations">${policy.options.map(option => `<p><strong>${esc(option.name)}:</strong> ${esc(option.description)}</p>`).join('')}</div><button class="button" type="submit" ${state.result || policy.cooldown ? 'disabled' : ''}>${policy.cooldown ? `Review in ${policy.cooldown} watches` : `Set ${esc(policy.name.toLowerCase())}`}</button></form>`).join('')}</div></details>
    <details class="social-disclosure"><summary>Officer bench <span>Train deputies and share the workload</span></summary><p class="caption social-notice">These officers are fictional campaign characters. Their personalities are authored for this simulation.</p><div class="cohort-grid">${report.officers.map(officer => `<article class="inner-panel" data-officer="${esc(officer.id)}"><h3>${esc(officer.name)} <span class="muted">· ${esc(officer.role)}</span></h3><p class="modal-copy">${esc(officer.description)}</p>${kv('Training level',String(officer.level))}<button class="button" data-action="peopleTrainOfficer" data-officer-id="${esc(officer.id)}" ${officer.trainingUntil > state.turn || officer.level >= 3 || state.result ? 'disabled' : ''}>${officer.trainingUntil > state.turn ? `Training through watch ${officer.trainingUntil}` : officer.level >= 3 ? 'Fully trained' : `Train deputy · ${money(officer.trainingCost)}`}</button></article>`).join('')}</div></details>
    <details class="social-disclosure"><summary>Corporation memory <span>Promises, recognition & disagreements</span></summary>${report.memories.length ? report.memories.slice(0, 12).map(memory => `<article class="event-row"><small>Watch ${memory.turn} · ${esc(memory.tone)}</small><strong>${esc(memory.title)}</strong><p>${esc(memory.text)}</p></article>`).join('') : '<p class="empty-state">Your decisions will become the corporation’s shared history.</p>'}</details>
  </section>`;
}

export function getCouncilReport(state) { return getDiplomacyReport(state); }

export function renderPolitics(state, organization, {esc, money, sys, systemOptions, options, labels}) {
  if (!organization) return '';
  const o = organization, pending = o.pending, locked = Boolean(state.result);
  return `<div class="politics-summary"><span class="badge ${o.status === 'withdrawn' ? 'warning' : 'good'}">${o.status === 'withdrawn' ? 'Outside coalition' : 'Coalition member'}</span><span>Grievance ${Math.round(o.grievance)}%</span><span>${o.favors} favor${o.favors === 1 ? '' : 's'}</span></div><p class="modal-copy"><strong>${esc(o.priority.label)}:</strong> ${esc(o.priority.description)}</p>${o.rivalry ? `<p class="caption">Friction with ${esc(o.rivalry.name)} · tension ${Math.round(o.rivalry.tension)}%</p>` : ''}
    ${pending ? `<section class="counteroffer" aria-label="Counteroffer"><div class="section-heading"><h3>Counteroffer · ${money(pending.requiredISK)}</h3><span class="badge warning">Expires watch ${pending.expiresTurn}</span></div><p class="modal-copy">${esc(pending.reason)} ${esc(pending.agreement)} agreement in ${esc(sys(pending.targetId).name)}.</p><div class="button-row"><button class="button primary" data-action="diplomacyAccept" data-ally-id="${esc(o.id)}" ${locked ? 'disabled' : ''}>Accept counteroffer · ${money(pending.requiredISK)}</button><button class="button" data-action="diplomacyDecline" data-ally-id="${esc(o.id)}" ${locked ? 'disabled' : ''}>Decline counteroffer</button></div></section>` : ''}
    <details class="social-disclosure"><summary>Negotiate an agreement <span>Support, defense, workshops & SRP</span></summary><form class="negotiation-form" data-negotiation-form="${esc(o.id)}"><div class="form-line"><label class="form-field">Agreement<select name="agreement">${(o.agreementOptions || []).map(agreement => `<option value="${esc(agreement.id)}">${esc(agreement.label)} · ${money(agreement.isk)}</option>`).join('')}</select></label><label class="form-field">System<select name="targetId">${systemOptions(state.player.stagingId)}</select></label></div><div class="form-line"><label class="form-field">Joint operation<select name="mission">${options(['offensive','defensive','patrol','advantage','hub'],'patrol',v => labels[v])}</select></label><label class="form-field">Offer in ISK<input name="offerISK" type="number" min="0" max="500000000" step="1000000" placeholder="Leave blank for fair quote"></label></div><div class="agreement-description modal-copy">${esc(o.agreementOptions?.[0]?.description || '')}</div><p class="caption">Offer 0 to request terms. A counteroffer reserves no funds until accepted.</p><button class="button" type="submit" ${o.status === 'withdrawn' || locked ? 'disabled' : ''}>Propose agreement</button></form></details>
    <details class="social-disclosure"><summary>Relationships & commitments <span>Favors, treaties & recent history</span></summary><div class="button-row relationship-actions"><button class="button" data-action="diplomacyAid" data-ally-id="${esc(o.id)}" ${o.cooldowns.aid || locked ? 'disabled' : ''}>Recovery aid · 20M ISK</button><button class="button" data-action="diplomacyCallFavor" data-ally-id="${esc(o.id)}" ${!o.favors || o.cooldowns.favor || locked ? 'disabled' : ''}>Call in a favor · 20M ISK</button><button class="button" data-action="diplomacyReconcile" data-ally-id="${esc(o.id)}" ${o.cooldowns.reconcile || locked ? 'disabled' : ''}>${o.status === 'withdrawn' ? 'Reopen coalition talks' : 'Repair relations'} · 10M ISK</button>${o.rivalry ? `<button class="button" data-action="diplomacyMediate" data-ally-id="${esc(o.id)}" ${o.cooldowns.mediate || locked ? 'disabled' : ''}>Mediate rivalry · 10M ISK</button>` : ''}</div><h4>Active agreements</h4>${o.agreements.length ? o.agreements.map(agreement => `<div class="queue-item"><strong>${esc(agreement.label)}</strong><br><span>${esc(sys(agreement.targetId)?.name || 'Coalition-wide')} · ${agreement.remainingTurns} watches${agreement.escrow ? ` · ${money(agreement.escrow)} escrow` : ''}</span>${agreement.description ? `<p>${esc(agreement.description)}</p>` : ''}<p>Ending early costs 8 trust and adds 15 grievance. Unused SRP escrow returns; paid service fees stay with the ally.</p><button class="button" data-action="diplomacyRenounce" data-ally-id="${esc(o.id)}" data-agreement-id="${esc(agreement.id)}" ${locked ? 'disabled' : ''}>End ${esc(agreement.label.toLowerCase())}</button></div>`).join('') : '<p class="empty-state">No active treaty obligations.</p>'}<h4>Relationship memory</h4>${o.memories.length ? o.memories.slice(0, 6).map(memory => `<article class="event-row"><small>Watch ${memory.turn} · ${esc(memory.event)}</small><p>${esc(memory.text)}</p></article>`).join('') : '<p class="empty-state">No shared history yet.</p>'}</details>`;
}
